name: model-evaluation

on:
  workflow_dispatch:

env:
  DEVICE_PAIRS: T4,V100;T4,A100

jobs:
  query-runners:
    name: Run on T4
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4

      - name: test step
        run: | 
          sudo chmod +x ./experiments/workflow_model_eval.sh
          ./experiments/workflow_model_eval.sh python3.10
        env:
          LOCAL_DEVICE: T4
