name: Test Workflow

on:
  workflow_dispatch:

jobs:
  whl-build-cu116:
    runs-on: [self-hosted, cu116]
    steps:
      - name: Display host information
        run: |
          uname -a
          hostname
          pwd
          id
          ls -la

      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Fetch submodules
        run: git submodule update --init --recursive

      - name: Build
        run: |
          python3.9 -m virtualenv venv -p python3.9
          source venv/bin/activate
          python -V
          cd analyzer && ./install-dev.sh

      - name: Test import
        run: |
          cd analyzer
          wget https://zenodo.org/record/4876277/files/habitat-models.tar.gz?download=1 -O habitat-models.tar.gz
          ./extract-models.sh habitat-models.tar.gz
          source ../venv/bin/activate && python -c "import habitat"

      - name: Generate wheel
        run: |
          source venv/bin/activate
          python -m pip install -U wheel setuptools
          cd analyzer
          python setup.py sdist bdist_wheel

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheel-cu116
          path: analyzer/dist/*.whl

  whl-build-cu113:
    runs-on: [self-hosted, cu113]
    steps:
      - name: Display host information
        run: |
          uname -a
          hostname
          pwd
          id
          ls -la

      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Fetch submodules
        run: git submodule update --init --recursive

      - name: Build
        run: |
          python3.9 -m virtualenv venv -p python3.9
          source venv/bin/activate
          python -V
          cd analyzer && ./install-dev.sh

      - name: Test import
        run: |
          cd analyzer
          wget https://zenodo.org/record/4876277/files/habitat-models.tar.gz?download=1 -O habitat-models.tar.gz
          ./extract-models.sh habitat-models.tar.gz
          source ../venv/bin/activate && python -c "import habitat"

      - name: Generate wheel
        run: |
          source venv/bin/activate
          python -m pip install -U wheel setuptools
          cd analyzer
          python setup.py sdist bdist_wheel

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheel-cu116
          path: analyzer/dist/*.whl

  whl-build-cu111:
    runs-on: [self-hosted, cu111]
    steps:
      - name: Display host information
        run: |
          uname -a
          hostname
          pwd
          id
          ls -la

      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Fetch submodules
        run: git submodule update --init --recursive

      - name: Build
        run: |
          python3.9 -m virtualenv venv -p python3.9
          source venv/bin/activate
          python -V
          cd analyzer && ./install-dev.sh

      - name: Test import
        run: |
          cd analyzer
          wget https://zenodo.org/record/4876277/files/habitat-models.tar.gz?download=1 -O habitat-models.tar.gz
          ./extract-models.sh habitat-models.tar.gz
          source ../venv/bin/activate && python -c "import habitat"

      - name: Generate wheel
        run: |
          source venv/bin/activate
          python -m pip install -U wheel setuptools
          cd analyzer
          python setup.py sdist bdist_wheel

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheel-cu116
          path: analyzer/dist/*.whl

  whl-build-cu102:
    runs-on: [self-hosted, cu102]
    steps:
      - name: Display host information
        run: |
          uname -a
          hostname
          pwd
          id
          ls -la

      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Fetch submodules
        run: git submodule update --init --recursive

      - name: Build
        run: |
          python3.9 -m virtualenv venv -p python3.9
          source venv/bin/activate
          python -V
          cd analyzer && ./install-dev.sh

      - name: Test import
        run: |
          cd analyzer
          wget https://zenodo.org/record/4876277/files/habitat-models.tar.gz?download=1 -O habitat-models.tar.gz
          ./extract-models.sh habitat-models.tar.gz
          source ../venv/bin/activate && python -c "import habitat"

      - name: Generate wheel
        run: |
          source venv/bin/activate
          python -m pip install -U wheel setuptools
          cd analyzer
          python setup.py sdist bdist_wheel

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheel-cu102
          path: analyzer/dist/*.whl
