name: Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Display host information
        run: |
          uname -a
          hostname
          pwd
          id

      - name: Build
        run: |
          virtualenv venv
          source venv/bin/activate
          python -V
          cd analysis && ./install-dev.sh
