name: Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Display host information
        run: |
          uname -a
          hostname
          pwd
          id
          ls -la

      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Fetch submodules
        run: git submodule update --init --recursive

      - name: Build
        run: |
          python3.9 -m virtualenv venv -p python3.9
          source venv/bin/activate
          python -V
          cd analyzer && ./install-dev.sh


