name: Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Display host information
        run: |
          uname -a
          hostname
          pwd
          id

      - name: Build
        run: cd habitat-cu116/analysis && ./install-dev.sh
