name: CI
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-region: us-east-1
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: CentML/GPUClusterSwitchGithubAction@v1.3.5
        with:
          mode: start
          github-token: ${{ secrets.CENTML_PAT }}
          t4: true
          a10g: false
          v100: false

  whl-build-cu117:
    runs-on:
      group: organization/t4
      labels: [cu117]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.HABITAT_AWS_ACCESS_KEY }}
          aws-region: ${{ secrets.HABITAT_AWS_REGION }}
          aws-secret-access-key: ${{ secrets.HABITAT_AWS_SECRET_ACCESS_KEY }}

      - name: Display host information
        run: |
          uname -a
          hostname
          pwd
          id
          ls -la

      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Build Python3.7 wheel
        run: |
          ./build_scripts/build_wheel.sh python3.7 cu117

      - name: Build Python3.8 wheel
        run: |
          ./build_scripts/build_wheel.sh python3.8 cu117

      - name: Build Python3.9 wheel
        run: |
          ./build_scripts/build_wheel.sh python3.9 cu117

      - name: Build Python3.10 wheel
        run: |
          ./build_scripts/build_wheel.sh python3.10 cu117

      - name: Upload wheels to S3
        run: |
          aws s3 cp analyzer/dist/ s3://centml-releases/habitat/wheels-cu117/ --recursive --include "*"

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner # required to get output from the start-runner job
      - whl-build-cu117 # required to wait when the main job is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-region: us-east-1
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      - name: Stop EC2 runner
        id: stop-ec2-runner
        uses: CentML/GPUClusterSwitchGithubAction@v1.3.5
        with:
          mode: stop
          github-token: ${{ secrets.CENTML_PAT }}
          t4: true # required to match the list above - otherwise the runners will not stop
          a10g: false # required to match the list above - otherwise the runners will not stop
          v100: false
