name: whl-build-all

on:
  workflow_dispatch:

jobs:
  create-habitat-index-html:
    needs: [whl-build-cu102, whl-build-cu111, whl-build-cu113, whl-build-cu116, whl-build-cu117]
    runs-on: [self-hosted]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.HABITAT_AWS_ACCESS_KEY }}
          aws-region: ${{ secrets.HABITAT_AWS_REGION }}
          aws-secret-access-key: ${{ secrets.HABITAT_AWS_SECRET_ACCESS_KEY }}

      - name: Create temporary directory
        run |
          mkdir /home/index_dir && cd /home/index_dir

      - name: Create index.html
        run: |
          python /home/builduser/ create_index.py habitat -f wheels-cu102 wheels-cu111 wheels-cu113 wheels-cu116 wheels-cu117

      - name: Upload to S3
        run: |
          aws s3 cp index.html s3://centml-habitat/habitat/

  whl-build-cu102:
    runs-on: [self-hosted, cu102]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.HABITAT_AWS_ACCESS_KEY }}
          aws-region: ${{ secrets.HABITAT_AWS_REGION }}
          aws-secret-access-key: ${{ secrets.HABITAT_AWS_SECRET_ACCESS_KEY }}

      - name: Display host information
        run: |
          uname -a
          hostname
          pwd
          id
          ls -la

      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Build Python3.7 wheel
        run: |
          /home/builduser/build_habitat.sh python3.7 py37

      - name: Build Python3.8 wheel
        run: |
          /home/builduser/build_habitat.sh python3.8 py38

      - name: Build Python3.9 wheel
        run: |
          /home/builduser/build_habitat.sh python3.9 py39

      - name: Build Python3.10 wheel
        run: |
          /home/builduser/build_habitat.sh python3.10 py310

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels-cu102
          path: analyzer/dist/*.whl
        
      - name: Upload wheels to S3
        run: |
          aws s3 cp analyzer/dist/ s3://centml-habitat/habitat/wheels-cu102 --recursive --exclude "*" --include "*.whl"
      
      - name: Create index.html
        run: |
          file_list=(*.whl) && python3 create_index.py habitat_cu102 -f ${file_list[@]}

      - name: Upload index.html to S3
        run: |
          aws s3 cp index.html s3://centml-habitat/habitat/wheels-cu102

  whl-build-cu111:
    runs-on: [self-hosted, cu111]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.HABITAT_AWS_ACCESS_KEY }}
          aws-region: ${{ secrets.HABITAT_AWS_REGION }}
          aws-secret-access-key: ${{ secrets.HABITAT_AWS_SECRET_ACCESS_KEY }}

      - name: Display host information
        run: |
          uname -a
          hostname
          pwd
          id
          ls -la

      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Build Python3.7 wheel
        run: |
          /home/builduser/build_habitat.sh python3.7 py37

      - name: Build Python3.8 wheel
        run: |
          /home/builduser/build_habitat.sh python3.8 py38

      - name: Build Python3.9 wheel
        run: |
          /home/builduser/build_habitat.sh python3.9 py39

      - name: Build Python3.10 wheel
        run: |
          /home/builduser/build_habitat.sh python3.10 py310

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels-cu111
          path: analyzer/dist/*.whl

      - name: Upload wheels to S3
        run: |
          aws s3 cp analyzer/dist/ s3://centml-habitat/habitat/wheels-cu111 --recursive --exclude "*" --include "*.whl"
      
      - name: Create index.html
        run: |
          file_list=(*.whl) && python3 create_index.py habitat_cu111 -f ${file_list[@]}

      - name: Upload index.html to S3
        run: |
          aws s3 cp index.html s3://centml-habitat/habitat/wheels-cu111

  whl-build-cu113:
    runs-on: [self-hosted, cu113]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.HABITAT_AWS_ACCESS_KEY }}
          aws-region: ${{ secrets.HABITAT_AWS_REGION }}
          aws-secret-access-key: ${{ secrets.HABITAT_AWS_SECRET_ACCESS_KEY }}

      - name: Display host information
        run: |
          uname -a
          hostname
          pwd
          id
          ls -la

      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Build Python3.7 wheel
        run: |
          /home/builduser/build_habitat.sh python3.7 py37

      - name: Build Python3.8 wheel
        run: |
          /home/builduser/build_habitat.sh python3.8 py38

      - name: Build Python3.9 wheel
        run: |
          /home/builduser/build_habitat.sh python3.9 py39

      - name: Build Python3.10 wheel
        run: |
          /home/builduser/build_habitat.sh python3.10 py310

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels-cu113
          path: analyzer/dist/*.whl
      
      - name: Upload wheels to S3
        run: |
          aws s3 cp analyzer/dist/ s3://centml-habitat/habitat/wheels-cu113 --recursive --exclude "*" --include "*.whl"
      
      - name: Create index.html
        run: |
          file_list=(*.whl) && python3 create_index.py habitat_cu113 -f ${file_list[@]}

      - name: Upload index.html to S3
        run: |
          aws s3 cp index.html s3://centml-habitat/habitat/wheels-cu113

  whl-build-cu116:
    runs-on: [self-hosted, cu116]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.HABITAT_AWS_ACCESS_KEY }}
          aws-region: ${{ secrets.HABITAT_AWS_REGION }}
          aws-secret-access-key: ${{ secrets.HABITAT_AWS_SECRET_ACCESS_KEY }}

      - name: Display host information
        run: |
          uname -a
          hostname
          pwd
          id
          ls -la

      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Build Python3.7 wheel
        run: |
          /home/builduser/build_habitat.sh python3.7 py37

      - name: Build Python3.8 wheel
        run: |
          /home/builduser/build_habitat.sh python3.8 py38

      - name: Build Python3.9 wheel
        run: |
          /home/builduser/build_habitat.sh python3.9 py39

      - name: Build Python3.10 wheel
        run: |
          /home/builduser/build_habitat.sh python3.10 py310

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels-cu116
          path: analyzer/dist/*.whl

      - name: Upload wheels to S3
        run: |
          aws s3 cp analyzer/dist/ s3://centml-habitat/habitat/wheels-cu116 --recursive --exclude "*" --include "*.whl"
      
      - name: Create index.html
        run: |
          file_list=(*.whl) && python3 create_index.py habitat_cu116 -f ${file_list[@]}

      - name: Upload index.html to S3
        run: |
          aws s3 cp index.html s3://centml-habitat/habitat/wheels-cu116

  whl-build-cu117:
    runs-on: [self-hosted, cu117]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.HABITAT_AWS_ACCESS_KEY }}
          aws-region: ${{ secrets.HABITAT_AWS_REGION }}
          aws-secret-access-key: ${{ secrets.HABITAT_AWS_SECRET_ACCESS_KEY }}
          
      - name: Display host information
        run: |
          uname -a
          hostname
          pwd
          id
          ls -la

      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Build Python3.7 wheel
        run: |
          /home/builduser/build_habitat.sh python3.7 py37

      - name: Build Python3.8 wheel
        run: |
          /home/builduser/build_habitat.sh python3.8 py38

      - name: Build Python3.9 wheel
        run: |
          /home/builduser/build_habitat.sh python3.9 py39

      - name: Build Python3.10 wheel
        run: |
          /home/builduser/build_habitat.sh python3.10 py310

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels-cu117
          path: analyzer/dist/*.whl

      - name: Upload wheels to S3
        run: |
          aws s3 cp analyzer/dist/ s3://centml-habitat/habitat/wheels-cu117 --recursive --exclude "*" --include "*.whl"
      
      - name: Create index.html
        run: |
          file_list=(*.whl) && python3 create_index.py habitat_cu117 -f ${file_list[@]}

      - name: Upload index.html to S3
        run: |
          aws s3 cp index.html s3://centml-habitat/habitat/wheels-cu117
