name: whl-build-all

on:
  workflow_dispatch:

jobs:
  whl-build-cu102:
    runs-on: [self-hosted, cu102]
    steps:
      - name: Display host information
        run: |
          uname -a
          hostname
          pwd
          id
          ls -la

      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Build Python3.7 wheel
        run: |
          /home/builduser/build_habitat.sh python3.7 py37

      - name: Build Python3.8 wheel
        run: |
          /home/builduser/build_habitat.sh python3.8 py38

      - name: Build Python3.9 wheel
        run: |
          /home/builduser/build_habitat.sh python3.9 py39

      - name: Build Python3.10 wheel
        run: |
          /home/builduser/build_habitat.sh python3.10 py310

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels-cu102
          path: analyzer/dist/*.whl


  whl-build-cu111:
    runs-on: [self-hosted, cu111]
    steps:
      - name: Display host information
        run: |
          uname -a
          hostname
          pwd
          id
          ls -la

      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Build Python3.7 wheel
        run: |
          /home/builduser/build_habitat.sh python3.7 py37

      - name: Build Python3.8 wheel
        run: |
          /home/builduser/build_habitat.sh python3.8 py38

      - name: Build Python3.9 wheel
        run: |
          /home/builduser/build_habitat.sh python3.9 py39

      - name: Build Python3.10 wheel
        run: |
          /home/builduser/build_habitat.sh python3.10 py310

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels-cu111
          path: analyzer/dist/*.whl

  whl-build-cu113:
    runs-on: [self-hosted, cu113]
    steps:
      - name: Display host information
        run: |
          uname -a
          hostname
          pwd
          id
          ls -la

      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Build Python3.7 wheel
        run: |
          /home/builduser/build_habitat.sh python3.7 py37

      - name: Build Python3.8 wheel
        run: |
          /home/builduser/build_habitat.sh python3.8 py38

      - name: Build Python3.9 wheel
        run: |
          /home/builduser/build_habitat.sh python3.9 py39

      - name: Build Python3.10 wheel
        run: |
          /home/builduser/build_habitat.sh python3.10 py310

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels-cu113
          path: analyzer/dist/*.whl

  whl-build-cu116:
    runs-on: [self-hosted, cu116]
    steps:
      - name: Display host information
        run: |
          uname -a
          hostname
          pwd
          id
          ls -la

      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Build Python3.7 wheel
        run: |
          /home/builduser/build_habitat.sh python3.7 py37

      - name: Build Python3.8 wheel
        run: |
          /home/builduser/build_habitat.sh python3.8 py38

      - name: Build Python3.9 wheel
        run: |
          /home/builduser/build_habitat.sh python3.9 py39

      - name: Build Python3.10 wheel
        run: |
          /home/builduser/build_habitat.sh python3.10 py310

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheels-cu116
          path: analyzer/dist/*.whl
